//* Error code mongoose unique
const ERROR_CODE_UNIQUE = 11000;

export { ERROR_CODE_UNIQUE };

//* custom error_code for AppError

const ERROR_CODE_EMAIL_NOT_FOUND = 511001;
const ERROR_CODE_WRONG_PASSWORD = 522000;
const ERROR_CODE_ITEM_NOT_FOUND = 533000;
const ERROR_CODE_FORBIDDEN = 500403;
const ERROR_CODE_PASSWORD_CONFIRMATION = 522001;
const ERROR_CODE_PASSWORD_EMPTY = 522002;
export {
  ERROR_CODE_EMAIL_NOT_FOUND,
  ERROR_CODE_WRONG_PASSWORD,
  ERROR_CODE_FORBIDDEN,
  ERROR_CODE_PASSWORD_CONFIRMATION,
  ERROR_CODE_PASSWORD_EMPTY,
  ERROR_CODE_ITEM_NOT_FOUND,
};
