const RESPONSE_CODE_GOOD = 200;
const RESPONSE_CODE_CREATED_SUCCESSFULLY = 201;
const RESPONSE_CODE_REDIRECT = 301;
const RESPONSE_CODE_BAD = 400;
const RESPONSE_CODE_FORBIDDEN = 403;
const RESPONSE_CODE_NOT_FOUND = 404;
const RESPONSE_CODE_SERVER_DOWN = 500;
export {
  RESPONSE_CODE_GOOD,
  RESPONSE_CODE_CREATED_SUCCESSFULLY,
  RESPONSE_CODE_REDIRECT,
  RESPONSE_CODE_BAD,
  RESPONSE_CODE_FORBIDDEN,
  RESPONSE_CODE_NOT_FOUND,
  RESPONSE_CODE_SERVER_DOWN,
};
